### ISSUE TITLE
trans, weight, X, y issue

### ISSUE THREAD

**Issue by mxlei01** [marrrcin/pandas-feature-union#1]
I think sklearn now uses `trans, X, y, weight` instead of `trans, weight, X, y`.

Since the PandasFeatureUnion error out on me, and checking [FeatureUnion](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/pipeline.py) uses a different ordering.

**Comment by marrrcin** [comment]
Thanks for the information, I will verify it and modify the code accordingly. I suppose that there was some change in sklearn.

**Comment by marrrcin** [comment]
Closing as @rodrigomverissimo submited PR for this.
